### ISSUE TITLE
Board does not work with UART

### ISSUE THREAD

**Issue by Kokorone** [makerbase-mks/MKS-SGEN_L-V2#1]
I have the SGen L V2 and I cannot get UART mode to work with the mks tmc2209 drivers. I have added the jumpers in the correct configuration for uart under the driver as well as configured marlin with uart and m122 enabled. Running m122 returns a bad response on all the drivers, meaning they are not connected with uart.

![image](https://user-images.githubusercontent.com/32761171/89691999-4bc86980-d8bf-11ea-9868-56329c672d0c.png)

**Comment by Kokorone** [comment]
This was no longer a problem when connected to a proper power supply, I was having this issue exclusively through usb. Closing ticket

**Comment by makerbase-mks** [comment]
Can you provide your motherboard jumpers setting picture and your configuration.h file?

**Comment by makerbase-mks** [comment]
OK!
