### ISSUE TITLE
what screen can i put on

### ISSUE THREAD

**Issue by patxinet** [makerbase-mks/MKS-SGEN_L-V2#11]
Hi, I have a mks sgen L v2 board, and I want to update my old 12864 lcd screen, but I don't know if with the new tft35 and ts35, I can take advantage of all the touch screen features and configurations, is it possible? or am I just going to get a 12864 lcd with a nicer look?
regards

**Comment by makerbase-mks** [comment]
You can use MKS TS35 , support 12864 Marlin UI, Color Marlin UI
https://fr.aliexpress.com/item/1005001446396197.html
![image](https://user-images.githubusercontent.com/12979070/93730251-6bf78200-fbfa-11ea-859c-257b2257af45.png)

**Comment by patxinet** [comment]
12864 lcd with a nicer look,no more

thanks

**Comment by makerbase-mks** [comment]
I will close it.
