### ISSUE TITLE
position of the hole for the encoder

### ISSUE THREAD

**Issue by patxinet** [makerbase-mks/MKS-SGEN_L-V2#12]
Hello, I have decided on the mks ts35 screen, but I need the exact measurements of the position of the hole for the encoder and the reset, since it does not appear in the drawings or plans, thanks

**Comment by makerbase-mks** [comment]
MKS TS35 Siez dxf: https://github.com/makerbase-mks/MKS-TFT-Hardware/tree/master/MKS%20TS35/MKS%20TS35%20V2.0_001

**Comment by patxinet** [comment]
ok, thanks
