### ISSUE TITLE
3 d touch stop working no auto level. its basic a advanced end stop 

### ISSUE THREAD

**Issue by helgjohn** [makerbase-mks/MKS-SGEN_L-V2#14]
Have an issue with 3d touch sensor it dosent seem to work after a short while It dosent mater if its mks or skr board same issue on both brands. The probe does its thing and collect all data about the bed and so on but does not use the collected data in order to adjust the nozzle. So the ting i have now is a advanced end stop. have disabled and enabled every ting i can think of that correspond to the sensor. And the only differ is some times it crash in to the bed. The only remedy i have had any suksess with is re installing marlin and then it works for a short while. So now i am lost for options. The video for installment by MKS is a bit messy but i have to the best of my ability followed the steps, there is no video for MKS SGenl v2 (1769 chip) so i guess the instructions are the same the same as Sgenl (1768 )

**Comment by makerbase-mks** [comment]
Marlin+3D touch : https://github.com/makerbase-mks/MKS-SGEN_L-V2/tree/master/Firmware/3D%20TOUCH
