### ISSUE TITLE
Extruder fan not working

### ISSUE THREAD

**Issue by Doyle4** [makerbase-mks/MKS-SGEN_L-V2#16]
I did a 1:1 copy of my configs for the MKS GEN L board and changed steppers and directions etc, but for the life of me can not get the Extruder fan to work, does anyone know where to change the pin or define a new pin please? it use to kick in around 50c automatically. 

Thanks!

**Comment by Doyle4** [comment]
#define E0_AUTO_FAN_PIN 7 is what my MKS GEN L was set too, and what the SGEN L V2 is set too, but its not working.

In the pins.h file there is no mention of pin 7 for the old board or new, pretty confusing

**Comment by Doyle4** [comment]
got it, P2_06 was needed, not 07

**Comment by ILGROSSOFA** [comment]
> got it, P2_06 was needed, not 07

Hi Doyle4, 
I have the same problem on my MKS SGEN L v2: where did you change value to P2_06? Thank you in advance!

**Comment by Doyle4** [comment]
@ILGROSSOFA 
Configuration_adv.h > #define E0_AUTO_FAN_PIN P2_06

**Comment by ILGROSSOFA** [comment]
> @ILGROSSOFA
> Configuration_adv.h > #define E0_AUTO_FAN_PIN P2_06

Now there is written:
#define E0_AUTO_FAN_PIN 7
#define E1_AUTO_FAN_PIN -1
#define E2_AUTO_FAN_PIN -1
#define E3_AUTO_FAN_PIN -1
#define E4_AUTO_FAN_PIN -1
#define E5_AUTO_FAN_PIN -1
#define E6_AUTO_FAN_PIN -1
#define E7_AUTO_FAN_PIN -1
#define CHAMBER_AUTO_FAN_PIN -1

#define EXTRUDER_AUTO_FAN_TEMPERATURE 50
#define EXTRUDER_AUTO_FAN_SPEED 255   // 255 == full speed
#define CHAMBER_AUTO_FAN_TEMPERATURE 30
#define CHAMBER_AUTO_FAN_SPEED 255

Is it correct to change from 7 to P2_06?

**Comment by ILGROSSOFA** [comment]
It looks like I have to add following command in pins_MKS_SGEN_L_V2.h file:
#define HEATER_1_PIN                       P2_06
Isn't it?

**Comment by ILGROSSOFA** [comment]
SOLVED!
In configuration.adv.h file:
#define E0_AUTO_FAN_PIN P2_06

**Comment by dplumly** [comment]
> 

Hi ILGROSSOFA,

I am having the same issue, but just defining: #define E0_AUTO_FAN_PIN P2_06 in configuration_adv.h throws and error - P2_06 not declared in scope. Is there something you needed to declare first? Thank you.

**Comment by ILGROSSOFA** [comment]
Are you using Arduino or Visual Studio Code?
I have used Visual Studio Code and it worked for me.

**Comment by dplumly** [comment]
> Are you using Arduino or Visual Studio Code? I have used Visual Studio Code and it worked for me.

I have used both. The way I did get it to work for anyone else that has this issue is I didn't use the terminal that said fan. In configuration_adv.h, I set my fan to E0_AUTO_FAN_PIN 7. I then took 2 jumpers and plugged the fan into E1 interface.

**Comment by truonghuutoanonenote** [comment]
simply just plug the fan to 12v output on top left conner and everything is done

**Comment by ezpzlmnsqz1337** [comment]
> > Are you using Arduino or Visual Studio Code? I have used Visual Studio Code and it worked for me.
> 
> I have used both. The way I did get it to work for anyone else that has this issue is I didn't use the terminal that said fan. In configuration_adv.h, I set my fan to E0_AUTO_FAN_PIN 7. I then took 2 jumpers and plugged the fan into E1 interface.

Indeed, define E0_AUTO_FAN_PIN 7 and use the E1 terminal, not the always on connector next to the stepper drivers.
