### ISSUE TITLE
Installing FES along side 3Dtouch

### ISSUE THREAD

**Issue by doug-scott** [makerbase-mks/MKS-SGEN_L-V2#17]
I received my MKS SGEN_L v2.0 the other day.  I am trying to configure the two components to work together.  Both pieces say to use pin P1_24, and to connect both devices to the same socket on the mainboard.  The videos do not directly mention the v2.0 motherboard, nor do they show having both devices working on the same board at the same time for any of their boards.  

I am not large on knowledge, but, in my simple way of looking at it, what is to stop me from using the Z- Endstop connector for the FES, using pin P1_24, and setup the way it shows in the video(except the part that leads you to the wrong file, but use the 1769 version of the pins file).  Then go follow the 3Dtouch video, and again recognize the different names for headers, and connect the two wire connector to the Z+ Endstop connector and use pin P1_25 where it says to set it to P1_24.  Would that work, or am I missing a lot of other changes that would need to be done?

The instructions on WIKI for 3Dtouch are somewhat confusing at the end.  It says:

3D Touch replace z-axis endstop
According to the "3D Touch replace z-axis endstop" requirements Connect motherboard

Firmware setting(after normal firmware setting)

Configuration.h
Enable: #define Z_MIN_PROBE_USES_Z_MIN_ENDSTOP_PIN
Enable: #define Z_SAFE_HOMING
Disable: //#define Z_MIN_PROBE_PIN P1_24

To me this says basically after you get it working, rebuild the firmware again after making those 3 changes, then install and reboot.  Is that what it means?  Can't see how that would even be required.

The online videos are great to have, but, trying to follow the order it is presented in does not work.  How is he managing to get it to work BEFORE he made changes to configuration files?

**Comment by makerbase-mks** [comment]
#18
