### ISSUE TITLE
12864 display not showing Babystep Z when Babystep X and Y are activated

### ISSUE THREAD

**Issue by doug-scott** [makerbase-mks/MKS-SGEN_L-V2#24]
I have enabled Babysteps for x, y, and z axis.  When I use the 12864 to adjust Babystep on the Z axis it is not listed.  It shows "Probe Z Offset".  When X and Y Babysteps are not enabled, it shows "Babystep Z".
My 12864 is defined as "REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER" in configuration.h.

![DSC_0263](https://user-images.githubusercontent.com/34754582/97092802-ef026280-1614-11eb-92a2-8c34b9ab4c69.JPG)
[Configuration.zip](https://github.com/makerbase-mks/MKS-SGEN_L-V2/files/5433706/Configuration.zip)

**Comment by mks-viva** [comment]
I think babystep Z is necessary, babystep X or Y is not very necessary.

**Comment by doug-scott** [comment]
I would imagine it was discussed at some time between developers, and they decided that there was a need for it, just not everyone.  I am simply pointing out that there is a bug in there, either in the hardware that may have a max number of fields for babystep labels, and it is one short of what is supported.  Or, a developer never considered the existence of babystep-x and y.

**Comment by Elzariant** [comment]
Actually, your Baby-step for Z is activated : "Probe Z offset" is Z-baby-step combined with M851 (means the value is stored in EEPROM for next print). 

`#define BABYSTEP_ZPROBE_OFFSET // Combine M851 Z and Babystepping` 

Note : Personnaly I agree with mks-viva about the usefulness of baby-stepping X or Y during a print.

**Comment by doug-scott** [comment]
I think that this issue can be closed.  It was more of an understanding issue than anything else.
