### ISSUE TITLE
Board not installing Marlin

### ISSUE THREAD

**Issue by tatoap3** [makerbase-mks/MKS-SGEN_L-V2#27]
Hi!

Anyone knows if on SGEN_L V2.0, if I want to use DIR/Step mode, I connect the same mode as you show on other boards? M0 M1 and M2 jumped with the pin on the middle? And on this mode do I need to use 5 or 3,3V? I use TMC2209 drivers.

**Comment by mks-viva** [comment]
Hi! 
If you use TMC2209 DIR/Step mode
1. You need use jumpers connect to motherboard's M0, M1; Driver IC power you can use 3.3V or 5V
![image](https://user-images.githubusercontent.com/16629551/99204433-9d528f80-27f0-11eb-974e-dc6aba9da87a.png)

If you use TMC2209 UART mode
1. Jumpers setting
![image](https://user-images.githubusercontent.com/16629551/99204555-01755380-27f1-11eb-91a2-9f65efba31c9.png)

2. If you use sensorless homing function, you need connect X-DIAG jumper and driver IC power connect to 3.3V
![image](https://user-images.githubusercontent.com/16629551/99204648-46998580-27f1-11eb-8abe-a8adac03f8db.png)

More information, you can refer to MKS SGEN_L V2 Wiki and link is: https://github.com/makerbase-mks/MKS-SGEN_L-V2/wiki

**Comment by mks-viva** [comment]
Is this problem solved?

**Comment by mks-viva** [comment]
Hi! I will close this issues temporarily.

**Comment by tatoap3** [comment]
Hi friend

Sorry to don't reply

I was trying to understand what is wrong, but I was without much time in
the past weeks

The printer I was trying to install didn't work with the board. I tried
with the makerbase display and with the one I had in the original kit, but
the motors don't move

I seted the same vref it was in the previous kit, did all the connections
right, checked over and over what could be wrong, but until now I don't
know what can be...

Now the printer is on one friend's home, if you can have a clue on what's
wrong and need any information please, let me know, so I ask him to take a
picture or check the information...

The original kit was mounted with an arduino mega and a ramps 1.4

Thanks for all the attention so far and sorry again for the time I took to
reply

Best regards

Otavio

Em dom, 13 de dez de 2020 22:47, mks-viva <notifications@github.com>
escreveu:

**Comment by mks-viva** [comment]
I suggest you follow my instructions to test it
