### ISSUE TITLE
Printer don't start if connected to USB

### ISSUE THREAD

**Issue by cizquierdof** [makerbase-mks/MKS-SGEN_L-V2#32]
I'm having issues with SGEN L V2. If I try to switch on the printer while connected via an active USB, firmware don't start it only shows slightly flashing screen. I must switch off the printer, disconnect USB and only then, switch on the printer.

**Comment by mks-viva** [comment]
Hi! I want to know what firmware version you using and can you provide firmware to me and i will test it?

**Comment by mks-viva** [comment]
Hi! If have not response, i will close this issues temporarily.
