### ISSUE TITLE
Bad autotune pid results

### ISSUE THREAD

**Issue by cizquierdof** [makerbase-mks/MKS-SGEN_L-V2#34]
I'm trying to autotune hotend pid 'm303 e0 s230 c8' but if I use the results I always get temperature runout error, in change if I use standard Marlin values the hotend works right

**Comment by mks-viva** [comment]
Hi! Can you provide your test it picture or vodies to me?

**Comment by mks-viva** [comment]
Hi! If have not response, i will close this issues temporarily.
