### ISSUE TITLE
How to change configuration to make a delta robot?

### ISSUE THREAD

**Issue by 12343954** [makerbase-mks/MKS-SGEN_L-V2#36]
I wanna make a delta robot via MKS-SGEN_L-V2 borad, TMC2225 and 57 steppers.
I burn the firmware `.\Firmware\Marlin-bugfix-2.0.x-MKS TS35+SGEN_L V2` into the board.

What can I do the next? 
How to change configuration to make a delta robot?
thank you !

![12-12-2020 19-23-12](https://user-images.githubusercontent.com/1804003/103390674-b6b95c00-4b50-11eb-9f41-821d2d8cae12.png)

**Comment by mks-viva** [comment]
Hi! You can refer to here: https://github.com/MarlinFirmware/Configurations/tree/import-2.0.x/config

**Comment by 12343954** [comment]
Thank you for reply.

I read that delta config, its robot like this, not my want.
![image](https://user-images.githubusercontent.com/1804003/103539064-59b40200-4ed2-11eb-8761-5e3d6eb8deec.png)

**Comment by mks-viva** [comment]
Ok!

**Comment by mks-viva** [comment]
I will close this issues temporarily.

**Comment by 12343954** [comment]
it was failed, when i meger the latest `marlin 2.0.8 + delta config 2.0.8 + MKS-SGEN_L-V2 + TS35 v2+ TMC2225`.
i selected `step/dir` mode, default driver type(No uncomment).

stepper motors can't move smoothly, they vibrate very strong.
