### ISSUE TITLE
PLEASE upgrade marlin to the latest version `CONFIGURATION_H_VERSION 020008`, I can not meger the latest config to your version `020006`!

### ISSUE THREAD

**Issue by 12343954** [makerbase-mks/MKS-SGEN_L-V2#39]
PLEASE upgrade marlin to the latest version as your "https://github.com/makerbase-mks/MKS-SGEN_L-V2/wiki/Marlin_firmware/README" suggestion.

The marlin example config version is `020008`, and there are lots of differences between the latest version and yours.

I can not meger the latest config to version `020006`! Please help, thank you !

![image](https://user-images.githubusercontent.com/1804003/103616936-481d3980-4f68-11eb-9457-7df0927b9775.png)

![image](https://user-images.githubusercontent.com/1804003/103616957-51a6a180-4f68-11eb-9737-0b0a90acea7f.png)

**Comment by mks-viva** [comment]
Hi! You want to update it to the latest version marlin?

**Comment by 12343954** [comment]
en, for now, yes, because I know nothing about marlin, I'm a novice.

I don't know how are these pins defined, and how to use stepper motor directly. I have a kinematic algorithm.

**Comment by mks-viva** [comment]
The latest version marlin firmware link: https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

**Comment by mks-viva** [comment]
Hi! I will close this issues temporarily.

**Comment by 12343954** [comment]
I suggest you upgrade the source code, because you are a hardware supplier. upgrade together with marlin is good for your market.
