### ISSUE TITLE
HW suggestion, no permanent pullups

### ISSUE THREAD

**Issue by flankerzo** [makerbase-mks/MKS-SGEN_L-V2#42]
Hi, This is not and issue but pull request for future HW revision nad SGEN.

Im using PNP endstop sensors, and on board are permanent pullUp resistors that i always need to desolder (GEN L, SGEN L).
It will be better if you replace resistor with diode, than you can use software pullUP and pullDown if needed, and input legs of IC will be better protected.
Same can be done with servo pins, put diode from signal to+5V for preventing over voltage.
Another upgrade will be 12V stabilisator for accesories, fan connectors, maybe with jumper to selected 12V from stabilisator or input voltage.
I think adition cost will be in range of 0,5 usd.
Many thanks, i hope some MKS design engineer will read this :)

**Comment by mks-viva** [comment]
Hi! Thank you very much for your feedback, we will collect more user needs
