### ISSUE TITLE
Marlin display setting for MKS TS35 with MKS SGEN_L-V2.0

### ISSUE THREAD

**Issue by ILGROSSOFA** [makerbase-mks/MKS-SGEN_L-V2#43]
Hello,
I'm compiling Marlin bugfix 2.0 firmware for my printer and I don't understand what's the difference between the 2 settings indicated in your kind instructions, as follows:

Color Marlin UI ==> You needn't change it. MKS has config is OK. Default is Color Marlin UI
12864 Marlin UI ==> Configuration.h : disenable #define TFT_480x320_SPI and enable #define SPI_GRAPHICAL_TFT

Please let me know if both are ok and the differences in view. 
Thank you very much in advance.
Best regards
Grosso

**Comment by mks-viva** [comment]
MKS SGEN_L V2 path marlin firmware (with TS35)  is Color Marli UI default, so, you needn't set it.
If you want to use 12864 Marlin UI, you need change it.
Color Marlin UI and 12864 Marli UI is eelong to two different styles.
