### ISSUE TITLE
Problem with EXP output

### ISSUE THREAD

**Issue by emrebulgur** [makerbase-mks/MKS-SGEN_L-V2#47]
I purchased two different MKS SGENL V2.0 from you for my printers. I use one of the motherboard without any problem, but the screen does not work on the other motherboard. I tried 3 different screens but none of them worked. I've tried different serial port configurations and settings. I've used the same screens on ramps and they all work. You can understand this by watching the video.When connecting the motherboard to the computer, the computer detects the motherboard. I even connected through the repaiter host and the epprom settings I made were successfully saved to the motherboard. I realized that the firmware writing process was successful, from the change of the firmware filename. I even sent m106 command on the repaiter host and the fans started working. I think there is a problem with EXP1 and EXP2 outputs.  https://streamable.com/26x9dy https://streamable.com/7f4luu

**Comment by mks-viva** [comment]
1. Cut it
![image](https://user-images.githubusercontent.com/16629551/108622532-6c7b9980-7474-11eb-90f6-77c0d65e8a1b.png)
2. Connect to board
![image](https://user-images.githubusercontent.com/16629551/108622561-91700c80-7474-11eb-80ff-c0b17ba2f80b.png)
