### ISSUE TITLE
How Configure sensorless Z+ 

### ISSUE THREAD

**Issue by Papipapito** [makerbase-mks/MKS-SGEN_L-V2#48]
Hello, i am preparing a delta with Sgen_v2 with 2209

I need configure sensorless-homing but the board not have plug to Z+¿ how configure Z? 

Regards

**Comment by mks-viva** [comment]
Hi! Z DIAG connect to Z-, like this
![image](https://user-images.githubusercontent.com/16629551/109944406-28f51b00-7d11-11eb-87ab-cec6ba39657f.png)
