### ISSUE TITLE
Stepper motor make a lot of noise with TMC2209

### ISSUE THREAD

**Issue by Magiquall** [makerbase-mks/MKS-SGEN_L-V2#55]
Hello

So I have the MKS SGEN_L V2 with your TMC2209, but the motors make a lot of noise.
Connected in Uart mode I followed your video tutorial HERE:
https://www.youtube.com/watch?v=eF8Mqa2Y3oo&ab_channel=MakerbaseTeam

But I found a conflicting video HERE: 
https://www.youtube.com/watch?v=vSgcH2wjCwY&ab_channel=MakerbaseTeam

So I'm lost, as I really have to put on my jumpers.
My motors are 2A max, I started with 900mv from VRef, but super noisy and vibrate a lot, then I went down from 100mv several times to reach 300mV or the motors no longer work. But at 400mV it's still very noisy. Unsuportable, impossible to leave an impression all night despite the printer is in another closed room.

Please Help

**Comment by mks-viva** [comment]
Hi! If you use TMC Uart mode, you set current by configuration_adv.h file
