### ISSUE TITLE
Marlin 2.0

### ISSUE THREAD

**Issue by Kyosuke33** [makerbase-mks/MKS-SGEN_L-V2#6]
Hello, i download the latest Marlin 2.0 but there is no Board MKS Sgen L V2.
You know when it will be availiable ?
Don't want to use yours but a fresh build.
Thank you.

**Comment by savenko-egor** [comment]
You need copy [this](https://github.com/makerbase-mks/MKS-SGEN_L-V2/blob/master/Firmware/Marlin-2.0.6/Marlin/src/pins/lpc1769/pins_MKS_SGEN_L_V2.h) file to your Marlin folder.

**Comment by Kyosuke33** [comment]
Ok, thank you !

**Comment by makerbase-mks** [comment]
We are following up and have suggested that marlin first add support for the MKS SGEN_L V2 motherboard, which is in progress

**Comment by makerbase-mks** [comment]
@Kyosuke33 @savenko-egor 
![image](https://user-images.githubusercontent.com/12979070/91920417-8d500700-ecfb-11ea-943c-912692949aa3.png)
Last version marlin has add it.
