### ISSUE TITLE
MKS TFT WiFi with ESP3D - possible wrong firmware

### ISSUE THREAD

**Issue by NeoMod** [makerbase-mks/MKS-SGEN_L-V2#62]
I own what should be the latest version of the SGEN L V2, and I tried following the instructions provided in the wiki to have the MKS TFT WIFI MODULE (essentially an ESP8266 on custom PCB) working with ESP3D.

Following the instructions (https://github.com/makerbase-mks/MKS-SGEN_L-V2/wiki/MKS_TFT_WIFI) I downloaded the two *bin files and flashed them.

The procedure was a success, but after rebooting the module the WiFi Network is different: it appears as an open network called "ESP-F33EB1" instead of the password-protected one mentioned in the guide.

Also, when connecting to this network (which has the IP class in the range of 192.168.4.x) nothing is loaded: the "index.html" filesystem can't be loaded.

I tried compiling and using the latest official version of ESP3D, which works and loads fine on the module, but it can't communicate with the board. 

Firmware used: [Marlin 2.0.7.2](https://github.com/MarlinFirmware/Marlin/releases/tag/2.0.7.2)
ESP3D version used: [Stable 2.1.1](https://github.com/luc-github/ESP3D/releases/tag/v2.1.1) and [Developer 3.0 Alpha](https://github.com/luc-github/ESP3D/tree/3.0)
ESP3D by MKS: downloaded as per indications in [MKS TFT WIFI Wiki](https://github.com/makerbase-mks/MKS-SGEN_L-V2/wiki/MKS_TFT_WIFI)
Hardware for ESP3D: tested both on MKS TFT WiFi ESP8266 (marked ESP-12s) and NodeMCU Dev Board v2
Results: ESP3D Official Version can compile and run, but no connection with motherboard; ESP3D by MKS can install but won't run (details above). 

Thanks a lot for any advice you could give.

**Comment by kacharros** [comment]
Me ocurre lo mismo.
ESP3D operativo en web pero sin conexión con la impresora, tanto en puerto WIFI como en AUX1.
¿Alguna solución?

**Comment by NeoMod** [comment]
I'm closing this issue sine it never received official support, and it seemed to me that this "feature" on that motherboard was more like "smoke and mirrors".

Also, as of today I moved away from MKS products so I can no longer provide insights on this problem. I'm sorry I couldn't be of any help @kacharros: my oonly advice at this point would be to change brand.
