### ISSUE TITLE
Help with MKS-SGEN_L-V2 + BTT TFT35 V2.0

### ISSUE THREAD

**Issue by DvoraNoob** [makerbase-mks/MKS-SGEN_L-V2#66]
I'm trying to connect the tft to board, but it doesn't work, I've tried boundrate of 250000 and 115200 along with serial_port 0, serial_port 0 and serial_port_2 -1, and serial_port -1 and serial_port_2 0

**Comment by mks-viva** [comment]
MKS SGEN_L V2，AUX-1 is serial0

**Comment by DvoraNoob** [comment]
> MKS SGEN_L V2，AUX-1 is serial0

But only serial port 0? Because I tried everything

**Comment by DvoraNoob** [comment]
Nnot solved
