### ISSUE TITLE
How to wire BTT TFT35 v3.0 to MKS SGEN L v2?

### ISSUE THREAD

**Issue by ZhuDaHai** [makerbase-mks/MKS-SGEN_L-V2#7]
The BigTree Tech TFT35 v3.0 TFT connector has 5v GND RX, TX and RST (reset) pins, but the MKS SGEN L v2.0 board AUX-1 connector does not have RST (reset).
How to hook up that display to this mainboard?
What needs to change in Marlin?
Thanks!

**Comment by makerbase-mks** [comment]
MKS SGEN_L V1 or V2
```
AUX-1                                      
5V  GND  TX   RX
5V  GND  NC  NC

5V connect to 5V
GND connect to GND
TX connect to TFT's RX
RX connect to TFT's TX
RST connect to TFT's RST
```
![image](https://user-images.githubusercontent.com/12979070/92701481-a18ea680-f382-11ea-9137-eabfe7732904.png)

**Comment by ZhuDaHai** [comment]
It's labeled 'TRST' on the board's pin diagram. So that's the same as just 'RST' ?
Thanks!

**Comment by makerbase-mks** [comment]
Sorry! You need connect RST to MKS SGEN_L V2 WIFI interface RST
![image](https://user-images.githubusercontent.com/12979070/92704093-48744200-f385-11ea-9f4a-903e47f92a5d.png)

**Comment by ZhuDaHai** [comment]
Ok. Thanks!

**Comment by jorgedelacasa** [comment]
Hola, buenas. Acabo de entrar y tengo dudas.Pro favor  al equipo de makerbase-mks.
Ayuda. He dejado de usar mi mkstft35 porque no logro comunicarme con mks sgen-l v1.0 y esta btt tft35 no se como ponerla.
Por favor ayudenme. Muchas gracias

**Comment by SemStal** [comment]
I've got the same question but with the v 1.0 which doesn't have a wifi break out. Is there a reset pin I can pull from somewhere else? I believe the pins layout says it should be pin 16.
