### ISSUE TITLE
firmware marlin 2.0.6 error platformio

### ISSUE THREAD

**Issue by patxinet** [makerbase-mks/MKS-SGEN_L-V2#9]
hi, can you update the firmware for marlin 2.0.6.1 for mks sgen L v2?
platformio produces errors when compiling this version marlin 2.0.6, it only works with the most recent (2.0.6.1)
Thank you

**Comment by Doyle4** [comment]
https://github.com/MarlinFirmware/Marlin/tree/bugfix-2.0.x

**Comment by makerbase-mks** [comment]
@patxinet 
The latest marlin bugfix 2.0.x has supported MKS SGEN_L V2 motherboard

**Comment by patxinet** [comment]
ok, thanks

**Comment by makerbase-mks** [comment]
Ok! I will close it.
